In [1]:
import numpy as np

1. Создать вектор с последовательными значениями в диапазоне от 10 до 49

In [31]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

 2. Создать двумерный массив с 1 на границе и 0 внутри

In [32]:
x_size, y_size = 5, 6
a = np.ones([x_size, y_size])
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

3. Посчитать медианы столбцов матрицы

In [34]:
a = np.random.randint(0, 10, (5, 6))
print(a)
np.median(a, axis=1)

[[2 0 0 9 5 0]
 [8 8 1 7 9 3]
 [2 7 6 5 9 9]
 [1 4 1 1 8 6]
 [6 2 6 1 3 5]]


array([1. , 7.5, 6.5, 2.5, 4. ])

4. Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы. Для X =
np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

In [14]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
print(X)
diag = np.diag(X)
print(diag[diag != 0].prod())


[[1 0 1]
 [2 0 2]
 [3 0 3]
 [4 4 4]]
3


5. Найти максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой. Для x =
np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

In [17]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(x)
prev_is_zero = (x[:-1]==0)
print(prev_is_zero)
print(np.max(x[1:][prev_is_zero]))

[6 2 0 3 0 0 5 7 0]
[False False  True False  True  True False False]
5


6. Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами.

In [36]:
X, Y = np.random.randint(0, 10, (2, 5)), np.random.randint(5, 15, (3, 5))

print(X[:, np.newaxis])
print(Y[np.newaxis, :])
print(np.sqrt(((X[:, np.newaxis] - Y[np.newaxis, :]) ** 2).sum(axis=2)))

[[[7 0 8 7 3]]

 [[9 4 1 7 8]]]
[[[ 8 13  5  9 13]
  [14 13 13  6  8]
  [13  7  7  8  7]]]
[[16.82260384 16.40121947 10.14889157]
 [11.26942767 15.84297952  7.93725393]]
